version: "3.8"
services:
  registery:
    image: gestiondeprojet-loginapp:latest
    container_name: registery
    environment:
      - APP_TYPE=registery
    networks:
      - internal_network

  worker1:
    image: gestiondeprojet-loginapp:latest
    container_name: worker1
    environment:
      - APP_TYPE=worker
      - HOSTNAME=worker1
    networks:
      - internal_network

  worker2:
    image: gestiondeprojet-loginapp:latest
    container_name: worker2
    environment:
      - APP_TYPE=worker
      - HOSTNAME=worker2
    networks:
      - internal_network

  worker3:
    image: gestiondeprojet-loginapp:latest
    container_name: worker3
    environment:
      - APP_TYPE=worker
      - HOSTNAME=worker3
    networks:
      - internal_network

  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loadbalancer
    environment:
      - APP_TYPE=loadbalancer
    ports:
      - "8001:8081" # Port 3000 pour l'équilibreur de charge
    depends_on:
      - registery
      - worker1
      - worker2
      - worker3
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
