version: "3.8"
services:
  registery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registery
    environment:
      - APP_TYPE=registery
    networks:
      - internal_network
  server:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: server
      environment:
        - APP_TYPE=server
      ports:
        - "8081:8081"
      networks:
        - internal_network

  node1:
      build:
        context: .
        dockerfile: Dockerfile.noeud
      container_name: node1
      privileged: true
      environment:
        - APP_TYPE=node
        - NODE_ID=node1
      ports:
        - "2375:2375"
      networks:
        - internal_network
      command: >
        sh -c "
          dockerd-entrypoint.sh & 
          while ! docker info; do
            sleep 1
          done;
          tail -f /dev/null
        "

  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loadbalancer
    environment:
      - APP_TYPE=loadbalancer
    ports:
      - "8001:8081"
    depends_on:
      - registery
    networks:
      - internal_network


networks:
  internal_network:
    driver: bridge
